---
- name: Copy MySQL script
  template: src=mysql.sh.j2 dest=$HOME/{{ work_dir }}/mysql/mysql.sh mode=0777

- name: Check if port 3306 is listening
  wait_for:
    host: 127.0.0.1
    port: 3306
    delay: 5
    state: started

- name: Create databases and read-only user
  command: $HOME/{{ work_dir }}/mysql/mysql.sh
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false
