---
- name: Copy MySQL script
  template: src=mysql.sh.j2 dest=/Users/{{ work_user }}/{{ work_dir }}/mysql/mysql.sh mode=0777

- name: Create databases and read-only user
  command: docker exec --tty tc-containers_mysql_1 /bin/bash /var/lib/mysql/mysql.sh
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false
