---
- name: Create nginx servers directory
  file:
    path: /usr/local/etc/nginx/servers
    state: directory
    mode: 0777

- name: Create nginx ssl directory
  file:
    path: /usr/local/etc/nginx/ssl
    state: directory
    mode: 0777

- name: Copy nginx configured files
  template: src=www.conf.j2 dest=/usr/local/etc/nginx/servers/home.{{ work_domain }}.conf

- name: Copy nginx ssl certificates
  copy:
    src: $HOME/{{ work_dir }}/home.{{ work_domain }}/docs/installation/ssl
    dest: /usr/local/etc/nginx
    remote_src: true

- name: Add root certificate to trust
  command: security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain /usr/local/etc/nginx/ssl/tenantcloud-rootCA.crt
  become: true
  changed_when: false

- name: Copy root private key certificate to minio folder
  copy:
    src: /usr/local/etc/nginx/ssl/km.dev.key
    dest: $HOME/.minio/private.key
    remote_src: true

- name: Copy root public key certificate to minio folder
  copy:
    src: /usr/local/etc/nginx/ssl/km.dev.crt
    dest: $HOME/.minio/public.crt
    remote_src: true

- name: Copy nginx ssl certificates to minio folder
  copy:
    src: /usr/local/etc/nginx/ssl/
    dest: $HOME/.minio
    remote_src: true

- name: Add hostname to hosts file
  become: true
  lineinfile:
    state: present
    line: 127.0.0.1 home.{{ work_domain }} {{ work_domain }} www.{{ work_domain }}
    create: true
    dest: /etc/hosts
