---
- name: Download minio bin file
  get_url:
    url: https://dl.min.io/client/mc/release/darwin-amd64/mc
    dest: /usr/local/bin/minio-client
    mode: '0777'

- name: Create s3 local project
  command: /usr/local/bin/minio-client config host add s3 https://home.tenantcloud.dev:9002 minio miniostorage
  changed_when: false

- name: Create s3 local backet
  command: /usr/local/bin/minio-client mb s3/local
  changed_when: false

- name: Create s3 tenantcloud-mobile backet
  command: /usr/local/bin/minio-client mb s3/tenantcloud-mobile
  changed_when: false

- name: Set s3 local backet policy
  command: /usr/local/bin/minio-client policy set public s3/local
  changed_when: false

- name: Set s3 tenantcloud-mobile backet policy
  command: /usr/local/bin/minio-client policy set public s3/tenantcloud-mobile
  changed_when: false
