---
- name: Copy docker enviromment file
  copy:
    src: /Users/{{ work_user }}/{{ work_dir }}/{{ docker_dir }}/.env.example
    dest: /Users/{{ work_user }}/{{ work_dir }}/{{ docker_dir }}/.env
    remote_src: true

- name: Change docker settings
  lineinfile:
    path: /Users/{{ work_user }}/.docker/config.json
    regexp: '  "credsStore'
    state: absent

- name: Remove docker-credential-osxkeychain
  file:
    path: /usr/local/bin/docker-credential-osxkeychain
    state: absent

- name: Docker login (must "--no-include-email")
  shell: "$(aws ecr get-login-password | docker login --username AWS \
  --password-stdin {{ aws_account_id }})"
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false

- name: Start services via docker-compose
  docker_compose:
    project_src: /Users/{{ work_user }}/{{ work_dir }}/{{ docker_dir }}
