---
- name: Copy docker enviromment file
  copy:
    src: /Users/{{ work_user }}/{{ work_dir }}/{{ docker_dir }}/.env.example
    dest: /Users/{{ work_user }}/{{ work_dir }}/{{ docker_dir }}/.env
    remote_src: true

- name: Remove docker-credential-osxkeychain
  file:
    path: /usr/local/bin/docker-credential-osxkeychain
    state: absent

- name: Docker login (must "--no-include-email")
  shell: "$(aws ecr get-login --region {{ aws_default_region }} --no-include-email)"
  args:
    executable: /bin/zsh
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  changed_when: false

- name: Start services via docker-compose
  docker_compose:
    project_src: /Users/{{ work_user }}/{{ work_dir }}/{{ docker_dir }}
